package lee.code.capture.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;
import org.bukkit.entity.EntityType;

@AllArgsConstructor
public enum SupportedEntity {
  SHEEP(EntityType.SHEEP),
  CHICKEN(EntityType.CHICKEN),
  PHANTOM(EntityType.PHANTOM),
  WOLF(EntityType.WOLF),
  CAT(EntityType.CAT),
  VILLAGER(EntityType.VILLAGER),
  BEE(EntityType.BEE),
  COW(EntityType.COW),
  ZOMBIE(EntityType.ZOMBIE),
  BLAZE(EntityType.BLAZE),
  SNIFFER(EntityType.SNIFFER),
  RABBIT(EntityType.RABBIT),
  SLIME(EntityType.SLIME),
  MAGMA_CUBE(EntityType.MAGMA_CUBE),
  RAVAGER(EntityType.RAVAGER),
  CREEPER(EntityType.CREEPER),
  SKELETON(EntityType.SKELETON),
  HORSE(EntityType.HORSE),
  COD(EntityType.COD),
  DOLPHIN(EntityType.DOLPHIN),
  GHAST(EntityType.GHAST),
  BAT(EntityType.BAT),
  ALLAY(EntityType.ALLAY),
  STRIDER(EntityType.STRIDER),
  SNOWMAN(EntityType.SNOWMAN),
  IRON_GOLEM(EntityType.IRON_GOLEM),
  ZOGLIN(EntityType.ZOGLIN),
  TURTLE(EntityType.TURTLE),
  AXOLOTL(EntityType.AXOLOTL),
  WITCH(EntityType.WITCH),
  MUSHROOM_COW(EntityType.MUSHROOM_COW),
  ENDERMAN(EntityType.ENDERMAN),
  CAMEL(EntityType.CAMEL),
  DONKEY(EntityType.DONKEY),
  FROG(EntityType.FROG),
  FOX(EntityType.FOX),
  SQUID(EntityType.SQUID),
  GLOW_SQUID(EntityType.GLOW_SQUID),
  OCELOT(EntityType.OCELOT),
  PARROT(EntityType.PARROT),
  PIG(EntityType.PIG),
  PUFFERFISH(EntityType.PUFFERFISH),
  SALMON(EntityType.SALMON),
  SKELETON_HORSE(EntityType.SKELETON_HORSE),
  ZOMBIE_HORSE(EntityType.ZOMBIE_HORSE),
  TADPOLE(EntityType.TADPOLE),
  TROPICAL_FISH(EntityType.TROPICAL_FISH),
  WANDERING_TRADER(EntityType.WANDERING_TRADER),
  SPIDER(EntityType.SPIDER),
  LLAMA(EntityType.LLAMA),
  GOAT(EntityType.GOAT),
  CAVE_SPIDER(EntityType.CAVE_SPIDER),
  PANDA(EntityType.PANDA),
  PIGLIN(EntityType.PIGLIN),
  ZOMBIFIED_PIGLIN(EntityType.ZOMBIFIED_PIGLIN),
  POLAR_BEAR(EntityType.POLAR_BEAR),
  HUSK(EntityType.HUSK),
  SILVERFISH(EntityType.SILVERFISH),
  ENDERMITE(EntityType.ENDERMITE),
  PILLAGER(EntityType.PILLAGER),
  GUARDIAN(EntityType.GUARDIAN),
  VEX(EntityType.VEX),
  DROWNED(EntityType.DROWNED),
  HOGLIN(EntityType.HOGLIN),
  PIGLIN_BRUTE(EntityType.PIGLIN_BRUTE),
  SHULKER(EntityType.SHULKER),
  STRAY(EntityType.STRAY),
  VINDICATOR(EntityType.VINDICATOR),
  WITHER_SKELETON(EntityType.WITHER_SKELETON),
  ZOMBIE_VILLAGER(EntityType.ZOMBIE_VILLAGER),
  EVOKER(EntityType.EVOKER),
  ILLUSIONER(EntityType.ILLUSIONER),
  TRADER_LLAMA(EntityType.TRADER_LLAMA)
  ;

  @Getter private final EntityType entityType;
}
